// Generated by Selenium IDE
package com.system.announcement.systemTesting;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;

public class CloseAnnouncementTest extends LoginTest {


  @BeforeEach
  public void setUp() {
    super.setUp();
    login("tatiana.costa@id.uff.br", "senha123");
  }

  @AfterEach
  public void tearDown() {
    super.tearDown();
  }

  @Test
  @DisplayName("Test will close the first announcement in 'My announcements' list")
  public void closeAnnouncement() {
    // Test name: close-announcement
    // Step # | name | target | value
    // 1 | open | / |
    driver.get("http://localhost:5173/");
    // 2 | click | linkText=Meus anúncios |
    driver.findElement(By.linkText("Meus anúncios")).click();
    // 3 | click | css=.grid-cols-1:nth-child(1) |
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    WebElement announcement = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".grid-cols-1:nth-child(1)")));
    announcement.click();
    // 5 | click | css=.text-gray-600 |
    WebDriverWait wait2 = new WebDriverWait(driver, Duration.ofSeconds(10));
    WebElement button = wait2.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("div.text-gray-600")));
    button.click();
    // 6 | assertConfirmation | Tem certeza que deseja fechar este anúncio? |
    assertThat(driver.switchTo().alert().getText(), is("Tem certeza que deseja fechar este anúncio?"));
    // 7 | webdriverChooseOkOnVisibleConfirmation | 
    driver.switchTo().alert().accept();
  }
}
