// Generated by Selenium IDE
package com.system.announcement.systemTesting;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

public class CreateAnnouncementTest extends LoginTest {

  @BeforeEach
  public void setUp() {
    super.setUp();
    login("tatiana.costa@id.uff.br", "senha123");
  }

  @AfterEach
  public void tearDown() {
    System.out.println("Última página visitada: " + driver.getCurrentUrl());
    super.tearDown();
  }

  // Creating a test announcement with 1 category
  public void criateAnnouncement(String title, String content, String city, String category, String price) {
    // Test name: criate-announcement
    // Step # | name | target | value
    // 1 | click | linkText=Criar anúncio |
    driver.findElement(By.linkText("Criar anúncio")).click();
    // 2 | click | name=title |
    driver.findElement(By.name("title")).click();
    // 3 | type | name=title | teste
    driver.findElement(By.name("title")).sendKeys(title);
    // 4 | click | name=content |
    driver.findElement(By.name("content")).click();
    // 5 | type | name=content | teste
    driver.findElement(By.name("content")).sendKeys(content);
    // 6 | click | id=react-select-2-placeholder |
    driver.findElement(By.id("react-select-2-input")).click();
    // 7 | click | //div[contains(text(), 'Niterói')] |
    String dynamicXpath1 = String.format("//div[contains(text(), '%s')]", city);
    driver.findElement(By.xpath(dynamicXpath1)).click();
    // 8 | click | id=react-select-3-placeholder |
    driver.findElement(By.id("react-select-3-input")).click();
    // 9 | click | //div[contains(text(), 'Aluguel')] |
    String dynamicXpath2 = String.format("//div[contains(text(), '%s')]", category);
    driver.findElement(By.xpath(dynamicXpath2)).click();
    // 10 | double click | name=price |
    {
      WebElement element = driver.findElement(By.name("price"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 11 | type | name=price | 55
    driver.findElement(By.name("price")).sendKeys(price);
    // 12 | click | css=.bg-blue-900 |
    driver.findElement(By.cssSelector(".bg-blue-900")).click();
  }

  @Test
  public void createAnnouncementTest() {
    criateAnnouncement("titulo teste", " descrição teste", "Niterói", "Aluguel", "60");
  }

}
