// Generated by Selenium IDE
package com.system.announcement.systemTesting;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;

public class LoginTest {
  public WebDriver driver;
  public Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  public void login(String email, String password) {
    // Test name: LOGIN
    // Step # | name | target | value
    // 1 | open | /login |
    driver.get("http://localhost:5173/login");
    // 2 | setWindowSize | 1936x1056 |
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | css=.border:nth-child(2) |
    // Select the "email" field
    driver.findElement(By.cssSelector(".border:nth-child(2)")).click();
    // 4 | type | css=.border:nth-child(2) | tatiana.costa@id.uff.br
    driver.findElement(By.cssSelector(".border:nth-child(2)")).sendKeys(email);
    // 5 | type | css=.border:nth-child(4) | senha123
    driver.findElement(By.cssSelector(".border:nth-child(4)")).sendKeys(password);
    // 6 | click | css=.bg-blue-900 |
    // Click "Entrar"
    driver.findElement(By.cssSelector(".bg-blue-900")).click();

    new WebDriverWait(driver, Duration.ofSeconds(10)).until(
        d -> d.getCurrentUrl().equals("http://localhost:5173/"));
  }

  @Test
  public void loginTest() {
    login("tatiana.costa@id.uff.br", "senha123");

    Assertions.assertEquals("http://localhost:5173/", driver.getCurrentUrl(), "Login falhou");
  }
}
